/**
 * Seed the local catalogue tables (species, sets, cards) from the bundled JSON
 * snapshot exported from the PullDex seed database.
 *
 * Idempotent: the snapshot's schema_version is recorded in app_meta. If the
 * stored version already matches, seeding is skipped. This runs offline on
 * first launch (and after a catalogue update) with no backend dependency.
 */

import type { SQLiteDatabase } from "expo-sqlite";

// Bundled snapshot (generated by scripts/export_catalogue.py). Metro bundles
// this JSON into the app. ~3.9 MB.
// eslint-disable-next-line @typescript-eslint/no-var-requires
import catalogue from "../../assets/catalogue/catalogue.json";

interface CatalogueSpecies {
  id: number;
  national_dex_number: number;
  name: string;
  generation: number | null;
}
interface CatalogueSet {
  id: number;
  api_set_id: string | null;
  name: string;
  series: string | null;
  release_date: string | null;
  is_promo: boolean;
}
interface CatalogueCard {
  id: number;
  api_card_id: string | null;
  pokemon_species_id: number | null;
  set_id: number | null;
  card_number: string | null;
  rarity: string | null;
  variant: string | null;
  image_url: string | null;
}
interface CatalogueSnapshot {
  schema_version: number;
  generated_at: string;
  counts: { species: number; sets: number; cards: number };
  species: CatalogueSpecies[];
  sets: CatalogueSet[];
  cards: CatalogueCard[];
}

const SNAPSHOT = catalogue as unknown as CatalogueSnapshot;
const META_KEY = "catalogue_schema_version";

async function getMeta(db: SQLiteDatabase, key: string): Promise<string | null> {
  const row = await db.getFirstAsync<{ value: string }>(
    "SELECT value FROM app_meta WHERE key = ?;",
    [key],
  );
  return row?.value ?? null;
}

async function setMeta(db: SQLiteDatabase, key: string, value: string): Promise<void> {
  await db.runAsync(
    "INSERT INTO app_meta(key, value) VALUES(?, ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value;",
    [key, value],
  );
}

/** Whether the catalogue needs (re)seeding for the current bundled snapshot. */
export async function catalogueNeedsSeed(db: SQLiteDatabase): Promise<boolean> {
  const stored = await getMeta(db, META_KEY);
  if (stored !== String(SNAPSHOT.schema_version)) return true;
  // Guard against a partially-seeded DB.
  const row = await db.getFirstAsync<{ n: number }>("SELECT COUNT(*) AS n FROM cards;");
  return (row?.n ?? 0) === 0;
}

/**
 * Seed catalogue tables from the bundled snapshot. Idempotent and transactional.
 * Uses INSERT OR REPLACE keyed on the catalogue ids so re-seeding is safe and
 * never duplicates rows. Collection data is never touched.
 */
export async function seedCatalogue(db: SQLiteDatabase): Promise<void> {
  if (!(await catalogueNeedsSeed(db))) return;

  await db.withExclusiveTransactionAsync(async (tx) => {
    // Catalogue is authoritative reference data — clear then bulk insert.
    await tx.execAsync("DELETE FROM cards; DELETE FROM sets; DELETE FROM pokemon_species;");

    for (const s of SNAPSHOT.species) {
      await tx.runAsync(
        "INSERT OR REPLACE INTO pokemon_species(id, national_dex_number, name, generation) VALUES(?,?,?,?);",
        [s.id, s.national_dex_number, s.name, s.generation],
      );
    }
    for (const st of SNAPSHOT.sets) {
      await tx.runAsync(
        "INSERT OR REPLACE INTO sets(id, api_set_id, name, series, release_date, is_promo) VALUES(?,?,?,?,?,?);",
        [st.id, st.api_set_id, st.name, st.series, st.release_date, st.is_promo ? 1 : 0],
      );
    }
    for (const c of SNAPSHOT.cards) {
      await tx.runAsync(
        "INSERT OR REPLACE INTO cards(id, api_card_id, pokemon_species_id, set_id, card_number, rarity, variant, image_url) VALUES(?,?,?,?,?,?,?,?);",
        [c.id, c.api_card_id, c.pokemon_species_id, c.set_id, c.card_number, c.rarity, c.variant, c.image_url],
      );
    }
  });

  await setMeta(db, META_KEY, String(SNAPSHOT.schema_version));
  await setMeta(db, "catalogue_generated_at", SNAPSHOT.generated_at);
}

export function catalogueCounts(): { species: number; sets: number; cards: number } {
  return SNAPSHOT.counts;
}
