"""initial database schema

Revision ID: 16f5cb78880c
Revises: 
Create Date: 2026-08-05 15:41:56.899886
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '16f5cb78880c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon_species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('national_dex_number', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pokemon_species_name'), 'pokemon_species', ['name'], unique=False)
    op.create_index(op.f('ix_pokemon_species_national_dex_number'), 'pokemon_species', ['national_dex_number'], unique=False)
    op.create_table('sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_set_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=150), nullable=False),
    sa.Column('series', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sets_api_set_id'), 'sets', ['api_set_id'], unique=False)
    op.create_index(op.f('ix_sets_name'), 'sets', ['name'], unique=False)
    op.create_index(op.f('ix_sets_series'), 'sets', ['series'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_card_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('pokemon_species_id', sa.Integer(), nullable=True),
    sa.Column('set_id', sa.Integer(), nullable=True),
    sa.Column('card_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('rarity', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('variant', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_species_id'], ['pokemon_species.id'], ),
    sa.ForeignKeyConstraint(['set_id'], ['sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_api_card_id'), 'cards', ['api_card_id'], unique=False)
    op.create_index(op.f('ix_cards_pokemon_species_id'), 'cards', ['pokemon_species_id'], unique=False)
    op.create_index(op.f('ix_cards_set_id'), 'cards', ['set_id'], unique=False)
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_card_id'), 'collection', ['card_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collection_card_id'), table_name='collection')
    op.drop_table('collection')
    op.drop_index(op.f('ix_cards_set_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_pokemon_species_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_api_card_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_sets_series'), table_name='sets')
    op.drop_index(op.f('ix_sets_name'), table_name='sets')
    op.drop_index(op.f('ix_sets_api_set_id'), table_name='sets')
    op.drop_table('sets')
    op.drop_index(op.f('ix_pokemon_species_national_dex_number'), table_name='pokemon_species')
    op.drop_index(op.f('ix_pokemon_species_name'), table_name='pokemon_species')
    op.drop_table('pokemon_species')
    # ### end Alembic commands ###
